### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by psyrendust** [emmetio/sublime-tern#23]
I'm running Sublime Text 2 v2.0.1, Build 2217 on OS X 10.8.4. I can't seem to get code completion working. Below you will find the console message from boot. I re-ran the `TernJS: Reload` command after boot.

Here is the console output:
```
startup, version: 2217 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/larrygordon/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 31 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 22 files for base name Main.sublime-menu
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Alignment/Alignment.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/ApplySyntax/ApplySyntax.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/ApplySyntax/is_rails_file.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_core.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_plugin.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_remove.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_swapping.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/bh_wrapping.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/BracketHighlighter/ure.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/CSScomb Alpha Sort/CSScomb.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Can I Use/useIt.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Clientside/Clientside.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Clientside/cssmin.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Clientside/jsbeautifier.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Clientside/jsmin.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/DocBlockr/jsdocs.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/EditorConfig/EditorConfig.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/FindKeyConflicts/find_key_conflicts.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/GitGutter/git_gutter.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/GitGutter/git_gutter_change.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/GitGutter/git_gutter_events.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/GitGutter/git_gutter_handler.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/GitGutter/git_helper.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/GitGutter/view_collection.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Grunt/main.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Insert Nums/insert_nums.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/JsFormat/js_formatter.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./js_formatter.py", line 34, in <module>
    import jsbeautifier, jsbeautifier.unpackers
ImportError: No module named unpackers
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/JsRun/JsRun.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Markdown Preview/MarkdownPreview.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Markdown Preview/markdown2.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Origami/origami.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Print to HTML/PrintToHTML.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Quick File Creator/SublimeQuickFileCreator.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/SCSS/scss_completions.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/SFTP/SFTP.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/SVN/SVN.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/SideBar.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/StatusBarFileSize.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/SideBarEnhancements/StatusBarModifiedTime.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/SublimeLinter/SublimeLinter.py
imported capp_lint
imported pep8
imported pyflakes
imported pyflakes.api
imported pyflakes.checker
imported pyflakes.messages
imported pyflakes.reporter
SublimeLinter: C loaded
SublimeLinter: c_cpplint loaded
SublimeLinter: CoffeeScript loaded
SublimeLinter: CSS loaded
SublimeLinter: Git Commit Message loaded
SublimeLinter: Ruby Haml loaded
SublimeLinter: haskell loaded
SublimeLinter: HTML loaded
SublimeLinter: Java loaded
SublimeLinter: JavaScript loaded
SublimeLinter: Lua loaded
SublimeLinter: Annotations loaded
SublimeLinter: Objective-J loaded
SublimeLinter: Perl loaded
SublimeLinter: PHP loaded
SublimeLinter: Puppet loaded
SublimeLinter: Python loaded
SublimeLinter: ruby-lint loaded
SublimeLinter: Ruby loaded
SublimeLinter: pylint loaded
SublimeLinter: XML loaded
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/SublimeStringEncode/string_encode.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Tag/Tag.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Tag/tag_close_tag.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Tag/tag_close_tag_on_slash.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Tag/tag_indent.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Tag/tag_insert_as_tag.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Tag/tag_lint.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Tag/tag_remove.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/Tag/tag_remove_attributes.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/TagWrapper/tag_wrapper.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/TernJS/tern.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/TidyHTML5/TidyHTML.py
Reloading plugin /Users/larrygordon/Library/Application Support/Sublime Text 2/Packages/tern_for_sublime/tern.py
plugin init time: 1.98915
loading bindings
loading pointer bindings
found 2 files for base name Soda Dark.sublime-theme
theme loaded
app ready
pre session restore time: 2.14712
using gamma: 2 (err: 6.9282)
wrote startup cache, added files: 2 orphaned files: 0 total files: 279 cache hits: 277
startup time: 2.31346 (package setup was not run)
TernJS: No need to update PyV8
Traceback (most recent call last):
  File "./tern.py", line 83, in init
    sync_all_projects()
  File "./tern.py", line 373, in sync_all_projects
    for p in all_projects():
  File "./tern.py", line 316, in all_projects
    proj = copy(project.all_projects())
  File "./ternjs/project.py", line 130, in all_projects
    result = [info(p) for p in projects_from_opened_files()]
  File "./ternjs/project.py", line 136, in info
    config = get_ternjs_config(project_id)
  File "./ternjs/project.py", line 63, in get_ternjs_config
    conf = json.load(open(project))
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ApplySyntax: Syntax file for INI does not exist at Packages/INI/INI.tmLanguage
Traceback (most recent call last):
  File "./sublime_plugin.py", line 175, in on_load
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 174, in <lambda>
  File "./tern.py", line 414, in on_load
    p = project.project_for_view(view)
  File "./ternjs/project.py", line 148, in project_for_view
    projects = all_projects()
  File "./ternjs/project.py", line 130, in all_projects
    result = [info(p) for p in projects_from_opened_files()]
  File "./ternjs/project.py", line 136, in info
    config = get_ternjs_config(project_id)
  File "./ternjs/project.py", line 63, in get_ternjs_config
    conf = json.load(open(project))
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "./sublime_plugin.py", line 175, in on_load
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 174, in <lambda>
  File "./tern.py", line 414, in on_load
    p = project.project_for_view(view)
  File "./ternjs/project.py", line 148, in project_for_view
    projects = all_projects()
  File "./ternjs/project.py", line 130, in all_projects
    result = [info(p) for p in projects_from_opened_files()]
  File "./ternjs/project.py", line 136, in info
    config = get_ternjs_config(project_id)
  File "./ternjs/project.py", line 63, in get_ternjs_config
    conf = json.load(open(project))
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
loaded 1052 snippets
Package Control: Skipping automatic upgrade, last run at 2013-06-28 16:57:28, next run at 2013-06-28 17:57:28 or after
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./tern.py", line 462, in run
    reload_ternjs()
  File "./tern.py", line 387, in reload_ternjs
    reset_all_projects()
  File "./tern.py", line 383, in reset_all_projects
    for p in all_projects():
  File "./tern.py", line 316, in all_projects
    proj = copy(project.all_projects())
  File "./ternjs/project.py", line 130, in all_projects
    result = [info(p) for p in projects_from_opened_files()]
  File "./ternjs/project.py", line 136, in info
    config = get_ternjs_config(project_id)
  File "./ternjs/project.py", line 63, in get_ternjs_config
    conf = json.load(open(project))
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Here is a copy of my .sublime-project file

```
{
  "folders": [{
    "path": ".",
    "folder_exclude_patterns": [
      "API",
      "App_Data",
      "bin",
      "Certificates",
      "Content",
      "Controllers",
      "Infrastructure",
      "Models",
      "nlog",
      "node_modules",
      "obj",
      "Properties",
      "Reporting",
      "Resources",
      "Service References",
      "ste-root",
      "Web References"
    ],
    "file_exclude_patterns": [
      "*.dll",
      "._*",
      ".png",
      "*.ashx*",
      "nlog.config",
      "packages.config",
      "*.asax*",
      "*.ico",
      "deploy.xml",
      "Error.htm",
      "*.csproj*",
      "*.sublime-workspace",
      "robots.txt"
    ]
  }],
  "ternjs": {
    "exclude": [
      "API/**",
      "App_Data/**",
      "bin/**",
      "Certificates/**",
      "Content/**",
      "Controllers/**",
      "Infrastructure/**",
      "Models/**",
      "nlog/**",
      "node_modules/**",
      "obj/**",
      "Properties/**",
      "Reporting/**",
      "Resources/**",
      "Service References/**",
      "ste-root/**",
      "Web References/**"
    ],
    "libs": [
      "browser",
      "jquery"
    ],
    "plugins": {
      "requirejs": {
        "baseURL": "./js"
      }
    }
  }
}
```

**Comment by psyrendust** [comment]
cleanup

**Comment by avckp** [comment]
In your project's .sublime-project file writing a valid json `{}` solved this for me.
